apiVersion: apps/v1
kind: Deployment
metadata:
  name: testepipe
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testepipe
  template:
    metadata:
      labels:
        app: testepipe
    spec:
      containers:
        - name: container-1
          image: swr.sa-brazil-1.myhuaweicloud.com/cloud-smt/teste.jp:${GIT_COMMIT}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: default-secret
